const Places_in_India = [
    ('Mumbai', 1),
    ('Hyderabad', 1),
    ('Bangalore', 1),
    ('Delhi', 1),
    ('Madhya Pradesh', 1),
    ('Gujarat', 1),
    ('Chennai', 1),
    ('Kerala', 1),
    ('Kashmir', 1),
    ('Sikkim', 1),
    ('Bihar', 1),
    ('Bhopal', 1),
    ('Dehradun', 1),
    ('Rayalaseema', 1),
    ('Guntur', 1),
    ('Uttar Pradesh', 1),
    ('Maharashtra', 1),
    ('Manipal', 1),
    ('Andaman', 1),
    ('Nicobar', 1),

    ('Taj Mahal', 1),
    ('Charminar', 1),
    ('Mysore Palace', 1),
    ('Vaishno Devi', 1),
    
    ('Qutub Minar', 1),
    ('Lotus Temple', 1),
    ('Red Fort', 1),
    ('Gateway of India', 1),
    ('Hawa Mahal', 1),
    ('Golden Temple', 1),
    ('Golconda Fort', 1),
]

const Indian_Food = [
    ('Pani Puri', 2),
    ('Dosa', 2),
    ('Idly', 2),
    ('Vada pav', 2),
    ('Kachori', 2),
    ('Biryani', 2),
    ('Tandoori chicken', 2),
    ('Samosa', 2),
    ('Chai', 2),
    ('Dhokla', 2),
    ('Jalebi', 2),
    ('Pav Bhaji', 2),
    ('Poha', 2),
    ('Rasmalai', 2),
    ('Paan', 2),
    ('Gutka', 2),
    ('Sugarcane', 2),
    ('Momos', 2),
    ('Mutton', 2),
    ('Shawarma', 2),
    ('Mandi', 2),
    ('Maggi', 2),
    ('Kelloggs', 2),
    ('Kaju Katli', 2),

    ('Haleem', 2),
    ('Dahi Puri', 2),
    ('Butter Chicken', 2),
]

const Indian_Brands = [
    ('Haldirams', 3),
    ('Maggi', 3),
    ('Chings', 3),
    ('Tanishq', 3),
    ('Pepsodent', 3),
    ('Colgate', 3),
    ('Lays', 3),
    ('Cheetos', 3),
    ('Dunkin Donuts', 3),
    ('Oreo', 3),
    ('Vimal Paan Masala', 3),

    ('Samsung', 3),
    ('TCS', 3),
    ('Capgemini', 3),
    ('Lux', 3), 
    ('Dove', 3),
    ('Santoor', 3),
    ('Amul', 3), 
    ('Reliance', 3), 
    ('Airtel', 3),
    ('Jio', 3),
    ('Maruti', 3), 
    ('L&T', 3), 
    ('SBI', 3),
    ('Dadu\'s', 3),
    ('Dominos', 3),
    ('Pizza Hut', 3),
    ('Baskin Robbins', 3),
    ('KFC', 3),
    ('McDonald\'s', 3),
    ('Coca Cola', 3),
    ('Pepsi', 3),
]

const countries = [
    ('United States', 4),
    ('India', 4),
    ('China', 4),
    ('Russia', 4),
    ('Algeria', 4),
    ('Australia', 4),
    ('Brazil', 4),
    ('Canada', 4),
    ('Denmark', 4),
    ('Egypt', 4),
    ('France', 4),
    ('Germany', 4),
    ('Iceland', 4),
    ('Japan', 4),
    ('Mexico', 4),
    ('United Kingdom', 4),
    ('Greece', 4),
    ('Turkey', 4),
    ('Ireland', 4),
    ('Spain', 4),
    ('Italy', 4),
    ('Netherlands', 4),
    ('Switzerland', 4),
    ('Sweden', 4),
    ('Norway', 4),
    ('Finland', 4),

    ('Nigeria', 4),
    ('South Africa', 4),
    ('New Zealand', 4),
    ('Bangladesh', 4),
    ('Pakistan', 4),
    ('Afghanistan', 4),
    ('Sri Lanka', 4),
    ('Indonesia', 4),
    ('Iraq', 4),
    ('Iran', 4),
    ('Turkmenistan', 4),
    ('Tajikistan', 4),
    ('Azerbaijan', 4),
    ('Uzbekistan', 4),
    ('Kyrgyzstan', 4),
    ('Jordan', 4),
    ('Morocco', 4),
    ('Albania', 4),
    ('Bosnia', 4),
    ('Serbia', 4),
    ('Moldova', 4),
];

const festivals = [
    ('Holi', 5),
    ('Diwali', 5),
    ('Sankranti', 5),
    ('Dussehra', 5),
    ('Saree Function', 5),
    ('Haldi Function', 5),
    ('Ganesh Chaturthi', 5),
    ('Muharram', 5),
    ('Eid-Ul-Fitr', 5),
    ('Christmas', 5),
    ('Easter', 5),

    ('Navratri', 5),
    ('Janmashtami', 5),
    ('Onam', 5),
    ('Rakhi', 5),
    ('Shivratri', 5),
    ('Gurpurab', 5),
]

const cartoons = [
    ('Tom & Jerry', 6),
    ('Doraemon', 6),
    ('Pokemon', 6),
    ('Ninja Hattori', 6),
    ('Oswald', 6),
    ('Scooby Doo', 6),
    ('Power Rangers', 6),
    ('Ben 10', 6),
    ('Oggy and the Cockroaches', 6),
    ('Jungle Book', 6),
    ('Tarzan', 6),
    ('Chota Bheem', 6),
    ('Kitaretsu', 6),
    ('Motu aur Patlu', 6),
    ('Shaktimaan', 6),

    ('Courage the Cowardly', 6),
    ('Avatar', 6),
    ('Mr. Bean', 6),
    ('Spiderman', 6),
    ('Kochikame', 6),
    ('He-man', 6),
    ('Hero', 6),
    ('PowerPuff Girls', 6),
    ('Johnny Bravo', 6),
    ('Dexter', 6),
    ('Kick Buttowski', 6),
    ('Looney Tunes', 6),
    ('Thomas the Train', 6),
    ('Dora the Explorer', 6),
    ('Bugs Bunny', 6),
    ('Teen Titans', 6),
    ('Samurai Jack', 6),
    ('Sonic', 6),
    ('Transformers', 6),
    ('SlugTerra', 6),
    ('Bob the Builder', 6),
    ('Noddy', 6),
    ('Aladdin', 6),
    ('Jackie Chan', 6),
    ('Justice League', 6),
    ('Stuart Little', 6),
    ('Popeye', 6),
    ('Superman', 6),
    ('Richie Rich', 6),
    ('Pink Panther', 6),
    ('Pingu', 6),
    ('Vikram aur Betaal', 6),
    ('Tenali Rama', 6),
]

Indian_Actions = [
    ('Broom', 7),
    ('Sabjiwala', 7),
    ('Gilli Danda', 7),
    ('Drying Clothes', 7),
    ('Washing Clothes', 7),
    ('Washing Utensils', 7),
    ('Pooja', 7),
    ('Activa Kickstart', 7),
    ('Chetak Start', 7),
    ('Traffic', 7),
    ('Bargain', 7),
    ('Namaste', 7),
    ('Meditation', 7),
    ('Yoga', 7),
    ('Dangal', 7),
    ('Kites', 7),
    ('Firecrackers', 7),
    ('Bharaat Dance', 7),
    ('Cameraman in Weddings', 7),

    ('Bajrang Dal', 7),
    ('Hookah', 7),
    ('Diwali Cleaning', 7),
    ('Oyo Rooms', 7),
    ('Swiggy', 7),
    ('Ola', 7),
    ('Chain Snatching', 7),

]

Bollywood = [
    ('Shah Rukh Khan', 8),
    ('Salman Khan', 8),
    ('Amitabh Bachchan', 8),
    ('Ranbir Kapoor', 8),
    ('Akshay Kumar', 8),
    ('Hrithik Roshan', 8),
    ('Tiger Shroff', 8),
    ('Jodha Akbar', 8),
    ('Katrina Kaif', 8),
    ('Deepika Padukone', 8),
    ('Sholay', 8),
    ('3 Idiots', 8),
    ('Taare Zameen Par', 8),
    ('Bhaag Milkha Bhaag', 8),
    ('Dangal', 8),
    ('Andhadhun', 8),
    ('ZNMD', 8),
    ('Karthik Calling Karthik', 8),
    ('Barfi', 8),
    ('MS Dhoni', 8),
    ('pk', 8),
    ('Ragini MMS', 8),
    ('Golmaal', 8),
    ('Welcome', 8),
    ('Rockstar', 8),
    ('Sanju', 8),
    ('Baahubali', 8),
    ('Vicky Donor', 8),
    ('DDLJ', 8),
    ('Pad Man', 8),
    ('Udta Punjab', 8),
    ('Lagaan', 8),
    ('Mary Kom', 8),
    ('Saawariya', 8),
    ('Devdas', 8),
    ('Dhoom', 8),
    ('Chak De India', 8),
    ('Brahmastra', 8),
    ('Gangubai', 8),

]

const IPL_Teams = [
    ('RCB', 9),
    ('Chennai Super Kings', 9),
    ('Delhi Capitals', 9),
    ('Gujarat Titans', 9),
    ('Kolkata Knight Riders', 9),
    ('Lucknow Super Giants', 9),
    ('Mumbai Indians', 9),
    ('Punjab Kings', 9),
    ('Rajasthan Royals', 9),
    ('Sunrisers Hyderabad', 9),
]

const indian_cricketers = [
    ('Virat Kohli', 10),
    ('Rohit Sharma', 10),
    ('Shubman Gill', 10),
    ('Bhuvneshwar Kumar', 10),
    ('Rishabh Pant', 10),
    ('Jasprit Bumrah', 10),
    ('Ravindra Jadeja', 10),
    ('Ravichandran Ashwin', 10),
    ('Mohammad Shami', 10),
    ('Mohammed Siraj', 10),
    ('Kl Rahul', 10),
    ('Hardik Pandya', 10),
    ('MS Dhoni', 10),
    ('Kapil Dev', 10),
    ('Sachin Tendulkar', 10),
    ('Rahul Dravid', 10),
    ('Sunil Gavaskar', 10),
    ('Anil Kumble', 10),
    ('Sourav Ganguly', 10),
    ('Virender Sehwag', 10),
    ('Yuvraj Singh', 10),
    ('Mohammad Azharuddin', 10),
    ('Javagal Srinath', 10),
    ('Harbhajan Singh', 10),
    ('Zaheer Khan', 10),
    ('VVS Laxman', 10),
    ('Gautam Gambhir', 10),
    ('Suresh Raina', 10),
    ('Murali Vijay', 10),
    ('Shikhar Dhawan', 10),
    ('Ajinkya Rahane', 10),
    ('Irfan Pathan', 10),
    ('Yusuf Pathan', 10),
    ('Wriddhiman Saha', 10),
    ('Kuldeep Yadav', 10),
]

// didnt add
const hyderabadi_things = [
    ('Blanket Hall', 13),
    ('Saleem Pheku', 13),
    ('Baigan', 13),
    ('Kiraak', 13),
    ('Item', 13),
    ('Charminar', 13),
    ('Begum Bazaar', 13),
    ('Irani Chai', 13),
    ('Niloufer', 13),
    ('Oyo Rooms', 13),
    ('Babri', 13),
    ('Maram pitti', 13),
    ('Necklace Road', 13),
    ('Indira Park', 13),
    ('Triple Riding', 13),
    ('Burqa', 13),
    ('Haleem', 13),
    ('Shawarma', 13),
    ('Kaan Bhairi', 13),
    ('Pinde me Miljana', 13),
    ('Kaiku?', 13),
    ('Yaaro', 13),
    ('Miya', 13),
    ('Teenmaar', 13),
    ('Marfa', 13),
    ('Dedh Hushaari', 13),
    ('Mothabari', 13),
    ('Galeez', 13),
    ('Amma Bava', 13),
    ('Howle', 13),
]

const being_telugu = [
    ('Ugadi', 16),
    ('Bonalu', 16),
    ('Bathukamma', 16),
    ('Pawan Kalyan', 16),
    ('Brahmanandam', 16),

]

// didnt add
const j90sThings = [
    ('Doordardhan', 17),
    ('TV Satellite shaking', 17),
    ('WWE', 17),

]

// didnt add
const Telugu_Memes = [
    ('Baane extralu', 18),
    ('Kurchi martapetti', 18),
    ('Uppal baal', 18),
    
]